/*
ROLLUP in SQL

Definition:
ROLLUP is an extension of the GROUP BY clause that allows you to calculate
multiple levels of subtotals across a specified group of columns. It
creates a hierarchical set of aggregation groups, moving from the most
detailed level down to a grand total. For example, ROLLUP(a, b) groups by
(a, b), then by (a), and finally by ().

Syntax Example:
SELECT
    col1,
    col2,
    SUM(col3)
FROM
    my_table
GROUP BY
    ROLLUP (col1, col2);

Use Cases:
1. Hierarchical Reporting: Generate subtotals for hierarchical data
   (e.g., Year > Quarter > Month, or Country > State > City).
2. Data Warehousing: Summarize data at different levels of granularity
   within a single query.
3. Financial Reports: Calculate totals and subtotals for balance sheets
   or expense reports.

Why use ROLLUP:
It simplifies query logic by replacing the need for multiple SELECT
statements combined with UNION ALL to get subtotals and grand totals.

Performance Implications and Pitfalls:
- Performance: ROLLUP is generally more efficient than computing multiple
  aggregates separately and unioning them, as it can often be performed
  in a single pass over the data.
- NULL values: The subtotal rows generated by ROLLUP contain NULLs for
  the columns that are not part of that specific grouping level. Be
  careful to distinguish these NULLs from actual NULL values present in
  the data (using GROUPING() function can help).
- Result Set Size: The number of rows returned increases with the number
  of columns in the rollup list.
*/

SELECT
    drivers.surname AS driver,
    constructors.name AS constructor,
    sum(results.points) AS points
FROM
    results
INNER JOIN races ON results.race_id = races.race_id
INNER JOIN drivers ON results.driver_id = drivers.driver_id
INNER JOIN constructors ON results.constructor_id = constructors.constructor_id
WHERE
    drivers.surname IN ('Prost', 'Senna')
GROUP BY
    rollup (drivers.surname, constructors.name);
