package main

import (
	"fmt"
	"log"
	"os"
	"strings"
)

var wordToMeaning = map[string]string{
	"YEAR":       "The time of the apparent revolution of the sun trough the ecliptic; the period occupied by the earth in making its revolution around the sun, called the astronomical year; also, a period more or less nearly agreeing with this, adopted by various nations as a measure of time, and called the civil year; as, the common lunar year of 354 days, still in use among the Mohammedans; the year of 360 days, etc. In common usage, the year consists of 365 days, and every fourth year (called bissextile, or leap year) of 366 days, a day being added to February on that year, on account of the excess above 365 days (see Bissextile).",
	"LIFE":       "The state of being which begins with generation, birth, or germination, and ends with death; also, the time during which this state continues; that state of an animal or plant in which all or any of its organs are capable of performing all or any of their functions; -- used of all animal and vegetable organisms.",
	"SCHOOL":     "A place for learned intercourse and instruction; an institution for learning; an educational establishment; a place for acquiring knowledge and mental training; as, the school of the prophets.",
	"FAMILY":     "A group of organisms, either animal or vegetable, related by certain points of resemblance in structure or development, more comprehensive than a genus, because it is usually based on fewer or less pronounced points of likeness. In zoology a family is less comprehesive than an order; in botany it is often considered the same thing as an order.",
	"GROUP":      "A variously limited assemblage of animals or plants, having some resemblance, or common characteristics in form or structure. The term has different uses, and may be made to include certain species of a genus, or a whole genus, or certain genera, or even several orders.",
	"HAND":       "Agency in transmission from one person to another; as, to buy at first hand, that is, from the producer, or when new; at second hand, that is, when no longer in the producer's hand, or when not new.",
	"GOVERNMENT": "The act of governing; the exercise of authority; the administration of laws; control; direction; regulation; as, civil, church, or family government.",
	"NUMBER":     "The distinction of objects, as one, or more than one (in some languages, as one, or two, or more than two), expressed (usually) by a difference in the form of a word; thus, the singular number and the plural number are the names of the forms of a word indicating the objects denoted or referred to by the word as one, or as more than one.",
	"NIGHT":      "That part of the natural day when the sun is beneath the horizon, or the time from sunset to sunrise; esp., the time between dusk and dawn, when there is no light of the sun, but only moonlight, starlight, or artificial light.",
	"HOME":       "A place of refuge and rest; an asylum; as, a home for outcasts; a home for the blind; hence, esp., the grave; the final rest; also, the native and eternal dwelling place of the soul.",
	"WATER":      "The limpidity and luster of a precious stone, especially a diamond; as, a diamond of the first water, that is, perfectly pure and transparent. Hence, of the first water, that is, of the first excellence.",
	"ROOM":       "Unobstructed spase; space which may be occupied by or devoted to any object; compass; extent of place, great or small; as, there is not room for a house; the table takes up too much room.",
	"FACT":       "The assertion or statement of a thing done or existing; sometimes, even when false, improperly put, by a transfer of meaning, for the thing done, or supposed to be done; a thing supposed or asserted to be done; as, history abounds with false facts.",
	"RIGHT":      "Of or pertaining to that side of the body in man on which the muscular action is usually stronger than on the other side; -- opposed to left when used in reference to a part of the body; as, the right side, hand, arm. Also applied to the corresponding side of the lower animals.",
	"JOB":        "A public transaction done for private profit; something performed ostensibly as a part of official duty, but really for private gain; a corrupt official business.",
	"HEAD":       "The source, fountain, spring, or beginning, as of a stream or river; as, the head of the Nile; hence, the altitude of the source, or the height of the surface, as of water, above a given place, as above an orifice at which it issues, and the pressure resulting from the height or from motion; sometimes also, the quantity in reserve; as, a mill or reservoir has a good head of water, or ten feet head; also, that part of a gulf or bay most remote from the outlet or the sea.",
	"HOUSE":      "A twelfth part of the heavens, as divided by six circles intersecting at the north and south points of the horizon, used by astrologers in noting the positions of the heavenly bodies, and casting horoscopes or nativities. The houses were regarded as fixed in respect to the horizon, and numbered from the one at the eastern horizon, called the ascendant, first house, or house of life, downward, or in the direction of the earth's revolution, the stars and planets passing through them in the reverse order every twenty-four hours.",
	"FRIEND":     "One of a religious sect characterized by disuse of outward rites and an ordained ministry, by simplicity of dress and speech, and esp. by opposition to war and a desire to live at peace with all men. They are popularly called Quakers.",
	"FATHER":     "A dignitary of the church, a superior of a convent, a confessor (called also father confessor), or a priest; also, the eldest member of a profession, or of a legislative assembly, etc.",
	"HOUR":       "The time of the day, as expressed in hours and minutes, and indicated by a timepiece; as, what is the hour? At what hour shall we meet?",
	"GAME":       "To play for a stake or prize; to use cards, dice, billiards, or other instruments, according to certain rules, with a view to win money or other thing waged upon the issue of the contest; to gamble.",
	"LAW":        "In philosophy and physics: A rule of being, operation, or change, so certain and constant that it is conceived of as imposed by the will of God or by some controlling authority; as, the law of gravitation; the laws of motion; the law heredity; the laws of thought; the laws of cause and effect; law of self-preservation.",
	"NAME":       "Reputed character; reputation, good or bad; estimation; fame; especially, illustrious character or fame; honorable estimation; distinction.",
	"BACK":       "In human beings, the hinder part of the body, extending from the neck to the end of the spine; in other animals, that part of the body which corresponds most nearly to such part of a human being; as, the back of a horse, fish, or lobster.",
	"FACE":       "Presence; sight; front; as in the phrases, before the face of, in the immediate presence of; in the face of, before, in, or against the front of; as, to fly in the face of danger; to the face of, directly to; from the face of, from the presence of.",
	"LEVEL":      "A line or surface to which, at every point, a vertical or plumb line is perpendicular; a line or surface which is everywhere parallel to the surface of still water; -- this is the true level, and is a curve or surface in which all points are equally distant from the center of the earth, or rather would be so if the earth were an exact sphere.",
	"HEALTH":     "The state of being hale, sound, or whole, in body, mind, or soul; especially, the state of being free from physical disease or pain.",
	"WAR":        "A contest between nations or states, carried on by force, whether for defence, for revenging insults and redressing wrongs, for the extension of commerce, for the acquisition of territory, for obtaining and establishing the superiority and dominion of one over the other, or for any other purpose; armed conflict of sovereign powers; declared and open hostilities.",
	"HISTORY":    "A systematic, written account of events, particularly of those affecting a nation, institution, science, or art, and usually connected with a philosophical explanation of their causes; a true story, as distinguished from a romance; -- distinguished also from annals, which relate simply the facts and events of each year, in strict chronological order; from biography, which is the record of an individual's life; and from memoir, which is history composed from personal experience, observation, and memory.",
	"RESULT":     "That which results; the conclusion or end to which any course or condition of things leads, or which is obtained by any process or operation; consequence or effect; as, the result of a course of action; the result of a mathematical operation.",
	"REASON":     "The faculty or capacity of the human mind by which it is distinguished from the intelligence of the inferior animals; the higher as distinguished from the lower cognitive faculties, sense, imagination, and memory, and in contrast to the feelings and desires. Reason comprises conception, judgment, reasoning, and the intuitional faculty. Specifically, it is the intuitional faculty, or the faculty of first truths, as distinguished from the understanding, which is called the discursive or ratiocinative faculty.",
	"RESEARCH":   "Diligent inquiry or examination in seeking facts or principles; laborious or continued search after truth; as, researches of human wisdom.",
	"GIRL":       "A female child, from birth to the age of puberty; a young maiden.",
	"GUY":        "A rope, chain, or rod attached to anything to steady it; as: a rope to steady or guide an object which is being hoisted or lowered; a rope which holds in place the end of a boom, spar, or yard in a ship; a chain or wire rope connecting a suspension bridge with the land on either side to prevent lateral swaying; a rod or rope attached to the top of a structure, as of a derrick, and extending obliquely to the ground, where it is fastened.",
	"AIR":        "A musical idea, or motive, rhythmically developed in consecutive single tones, so as to form a symmetrical and balanced whole, which may be sung by a single voice to the stanzas of a hymn or song, or even to plain prose, or played upon an instrument; a melody; a tune; an aria.",
	"FORCE":      "Strength or energy of body or mind; active power; vigor; might; often, an unusual degree of strength or energy; capacity of exercising an influence or producing an effect; especially, power to persuade, or convince, or impose obligation; pertinency; validity; special signification; as, the force of an appeal, an argument, a contract, or a term.",
	"FOOT":       "The lowest part or base; the ground part; the bottom, as of a mountain or column; also, the last of a row or series; the end or extremity, esp. if associated with inferiority; as, the foot of a hill; the foot of the procession; the foot of a class; the foot of the bed.",
	"AGE":        "That part of the duration of a being or a thing which is between its beginning and any given time; as, what is the present age of a man, or of the earth?",
	"NATION":     "A part, or division, of the people of the earth, distinguished from the rest by common descent, language, or institutions; a race; a stock.",
	"FIELD":      "The whole surface of an escutcheon; also, so much of it is shown unconcealed by the different bearings upon it. See Illust. of Fess, where the field is represented as gules (red), while the fess is argent (silver).",
	"ROLE":       "A part, or character, performed by an actor in a drama; hence, a part of function taken or assumed by any one; as, he has now taken the role of philanthropist.",
	"HEART":      "The seat of the affections or sensibilities, collectively or separately, as love, hate, joy, grief, courage, and the like; rarely, the seat of the understanding or will; -- usually in a good sense, when no epithet is expressed; the better or lovelier part of our nature; the spring of all our actions and purposes; the seat of moral life and character; the moral affections and character itself; the individual disposition and character; as, a good, tender, loving, bad, hard, or selfish heart.",
	"LIGHT":      "The manner in which the light strikes upon a picture; that part of a picture which represents those objects upon which the light is supposed to fall; the more illuminated part of a landscape or other scene; -- opposed to shade.  Cf. Chiaroscuro.",
	"TABLE":      "Any collection and arrangement in a condensed form of many particulars or values, for ready reference, as of weights, measures, currency, specific gravities, etc.; also, a series of numbers following some law, and expressing particular values corresponding to certain other numbers on which they depend, and by means of which they are taken out for use in computations; as, tables of logarithms, sines, tangents, squares, cubes, etc.; annuity tables; interest tables; astronomical tables, etc.",
	"GO":         "To pass from one place to another; to be in motion; to be in a state not motionless or at rest; to proceed; to advance; to make progress; -- used, in various applications, of the movement of both animate and inanimate beings, by whatever means, and also of the movements of the mind; also figuratively applied.",
	"GET":        "To arrive at, or bring one's self into, a state, condition, or position; to come to be; to become; -- with a following adjective or past participle belonging to the subject of the verb; as, to get sober; to get awake; to get beaten; to get elected.",
	"TAKE":       "To assume; to adopt; to acquire, as shape; to permit to one's self; to indulge or engage in; to yield to; to have or feel; to enjoy or experience, as rest, revenge, delight, shame; to form and adopt, as a resolution; -- used in general senses, limited by a following complement, in many idiomatic phrases; as, to take a resolution; I take the liberty to say.",
	"WANT":       "The state of not having; the condition of being without anything; absence or scarcity of what is needed or desired; deficiency; lack; as, a want of power or knowledge for any purpose; want of food and clothing.",
	"GIVE":       "To devote; to apply; used reflexively, to devote or apply one's self; as, the soldiers give themselves to plunder; also in this sense used very frequently in the past participle; as, the people are given to luxury and pleasure; the youth is given to study.",
	"USE":        "The benefit or profit of lands and tenements. Use imports a trust and confidence reposed in a man for the holding of lands. He to whose use or benefit the trust is intended shall enjoy the profits. An estate is granted and limited to A for the use of B.",
	"FIND":       "To meet with, or light upon, accidentally; to gain the first sight or knowledge of, as of something new, or unknown; hence, to fall in with, as a person.",
	"FEEL":       "To perceive by the touch; to take cognizance of by means of the nerves of sensation distributed all over the body, especially by those of the skin; to have sensation excited by contact of (a thing) with the body or limbs.",
	"LEAVE":      "To put; to place; to deposit; to deliver; to commit; to submit -- with a sense of withdrawing one's self from; as, leave your hat in the hall; we left our cards; to leave the matter to arbitrators.",
	"CALL":       "To summon to the discharge of a particular duty; to designate for an office, or employment, especially of a religious character; -- often used of a divine summons; as, to be called to the ministry; sometimes, to invite; as, to call a minister to be the pastor of a church.",
	"GOOD":       "Possessing desirable qualities; adapted to answer the end designed; promoting success, welfare, or happiness; serviceable; useful; fit; excellent; admirable; commendable; not bad, corrupt, evil, noxious, offensive, or troublesome, etc.",
	"NEW":        "Having existed, or having been made, but a short time; having originated or occured lately; having recently come into existence, or into one's possession; not early or long in being; of late origin; recent; fresh; modern; -- opposed to old, as, a new coat; a new house; a new book; a new fashion.",
	"FIRST":      "The upper part of a duet, trio, etc., either vocal or instrumental; -- so called because it generally expresses the air, and has a preeminence in the combined effect.",
	"LAST":       "A load; a heavy burden; hence, a certain weight or measure, generally estimated at 4,000 lbs., but varying for different articles and in different countries. In England, a last of codfish, white herrings, meal, or ashes, is twelve barrels; a last of corn, ten quarters, or eighty bushels, in some parts of England, twenty-one quarters; of gunpowder, twenty-four barrels, each containing 100 lbs; of red herrings, twenty cades, or 20,000; of hides, twelve dozen; of leather, twenty dickers; of pitch and tar, fourteen barrels; of wool, twelve sacks; of flax or feathers, 1,700 lbs.",
	"GREAT":      "Older, younger, or more remote, by single generation; -- often used before grand to indicate one degree more remote in the direct line of descent; as, great-grandfather (a grandfather's or a grandmother's father), great-grandson, etc.",
	"HIGH":       "Possessing a characteristic quality in a supreme or superior degree; as, high (i. e., intense) heat; high (i. e., full or quite) noon; high (i. e., rich or spicy) seasoning; high (i. e., complete) pleasure; high (i. e., deep or vivid) color; high (i. e., extensive, thorough) scholarship, etc.",
	"LARGE":      "Exceeding most other things of like kind in bulk, capacity, quantity, superficial dimensions, or number of constituent units; big; great; capacious; extensive; -- opposed to small; as, a large horse; a large house or room; a large lake or pool; a large jug or spoon; a large vineyard; a large army; a large city.",
	"NEXT":       "In the time, place, or order nearest or immediately suceeding; as, this man follows next.",
	"EARLY":      "In advance of the usual or appointed time; in good season; prior in time; among or near the first; -- opposed to late; as, the early bird; an early spring; early fruit.",
	"YOUNG":      "Not long born; still in the first part of life; not yet arrived at adolescence, maturity, or age; not old; juvenile; -- said of animals; as, a young child; a young man; a young fawn.",
	"BAD":        "Wanting good qualities, whether physical or moral; injurious, hurtful, inconvenient, offensive, painful, unfavorable, or defective, either physically or morally; evil; vicious; wicked; -- the opposite of good; as, a bad man; bad conduct; bad habits; bad soil; bad health; bad crop; bad news.",
	"ABLE":       "Having sufficient power, strength, force, skill, means, or resources of any kind to accomplish the object; possessed of qualifications rendering competent for some end; competent; qualified; capable; as, an able workman, soldier, seaman, a man able to work; a mind able to reason; a person able to be generous; able to endure pain; able to play on a piano.",
	"HOLD":       "To prosecute, have, take, or join in, as something which is the result of united action; as to, hold a meeting, a festival, a session, etc.; hence, to direct and bring about officially; to conduct or preside at; as, the general held a council of war; a judge holds a court; a clergyman holds a service.",
	"HAPPEN":     "To come by chance; to come without previous expectation; to fall out.",
	"LEARN":      "To gain knowledge or information of; to ascertain by inquiry, study, or investigation; to receive instruction concerning; to fix in the mind; to acquire understanding of, or skill; as, to learn the way; to learn a lesson; to learn dancing; to learn to skate; to learn the violin; to learn the truth about something.",
	"LEAD":       "One of the elements, a heavy, pliable, inelastic metal, having a bright, bluish color, but easily tarnished. It is both malleable and ductile, though with little tenacity, and is used for tubes, sheets, bullets, etc. Its specific gravity is 11.37. It is easily fusible, forms alloys with other metals, and is an ingredient of solder and type metal. Atomic weight, 206.4. Symbol Pb (L. Plumbum). It is chiefly obtained from the mineral galena, lead sulphide.",
	"UNDERSTAND": "To have just and adequate ideas of; to apprehended the meaning or intention of; to have knowledge of; to comprehend; to know; as, to understand a problem in Euclid; to understand a proposition or a declaration; the court understands the advocate or his argument; to understand the sacred oracles; to understand a nod or a wink.",
	"WATCH":      "That part, usually one half, of the officers and crew, who together attend to the working of a vessel for an allotted time, usually four hours. The watches are designated as the port watch, and the starboard watch.",
	"FOLLOW":     "To watch, as a receding object; to keep the eyes fixed upon while in motion; to keep the mind upon while in progress, as a speech, musical performance, etc.; also, to keep up with; to understand the meaning, connection, or force of, as of a course of thought or argument.",
	"READ":       "To go over, as characters or words, and utter aloud, or recite to one's self inaudibly; to take in the sense of, as of language, by interpreting the characters with which it is expressed; to peruse; as, to read a discourse; to read the letters of an alphabet; to read figures; to read the notes of music, or to read music; to read a book.",
	"GROW":       "To increase in size by a natural and organic process; to increase in bulk by the gradual assimilation of new matter into the living organism; -- said of animals and vegetables and their organs.",
	"WALK":       "That in or through which one walks; place or distance walked over; a place for walking; a path or avenue prepared for foot passengers, or for taking air and exercise; way; road; hence, a place or region in which animals may graze; place of wandering; range; as, a sheep walk.",
	"REMEMBER":   "To have ( a notion or idea) come into the mind again, as previously perceived, known, or felt; to have a renewed apprehension of; to bring to mind again; to think of again; to recollect; as, I remember the fact; he remembers the events of his childhood; I cannot remember dates.",
	"FALL":       "To decline in power, glory, wealth, or importance; to become insignificant; to lose rank or position; to decline in weight, value, price etc.; to become less; as, the falls; stocks fell two points.",
	"REACH":      "An extended portion of land or water; a stretch; a straight portion of a stream or river, as from one turn to another; a level stretch, as between locks in a canal; an arm of the sea extending up into the land.",
	"KILL":       "A channel or arm of the sea; a river; a stream; as, the channel between Staten Island and Bergen Neck is the Kill van Kull, or the Kills; -- used also in composition; as, Schuylkill, Catskill, etc.",
	"REMAIN":     "To stay behind while others withdraw; to be left after others have been removed or destroyed; to be left after a number or quantity has been subtracted or cut off; to be left as not included or comprised.",
	"RAISE":      "To bring to a higher condition or situation; to elevate in rank, dignity, and the like; to increase the value or estimation of; to promote; to exalt; to advance; to enhance; as, to raise from a low estate; to raise to office; to raise the price, and the like.",
	"REQUIRE":    "To demand; to insist upon having; to claim as by right and authority; to exact; as, to require the surrender of property.",
	"REPORT":     "An official statement of facts, verbal or written; especially, a statement in writing of proceedings and facts exhibited by an officer to his superiors; as, the reports of the heads af departments to Congress, of a master in chancery to the court, of committees to a legislative body, and the like.",
	"RETURN":     "The continuation in a different direction, most often at a right angle, of a building, face of a building, or any member, as a molding or mold; -- applied to the shorter in contradistinction to the longer; thus, a facade of sixty feet east and west has a return of twenty feet north and south.",
	"HOPE":       "A desire of some good, accompanied with an expectation of obtaining it, or a belief that it is obtainable; an expectation of something which is thought to be desirable; confidence; pleasing expectancy.",
	"RECEIVE":    "To take, as something that is offered, given, committed, sent, paid, or the like; to accept; as, to receive money offered in payment of a debt; to receive a gift, a message, or a letter.",
	"AGREE":      "To harmonize in opinion, statement, or action; to be in unison or concord; to be or become united or consistent; to concur; as, all parties agree in the expediency of the law.",
	"HIT":        "To reach or attain exactly; to meet according to the occasion; to perform successfully; to attain to; to accord with; to be conformable to; to suit.",
	"EAT":        "To corrode, as metal, by rust; to consume the flesh, as a cancer; to waste or wear away; to destroy gradually; to cause to disappear.",
	"FREE":       "To make free; to set at liberty; to rid of that which confines, limits, embarrasses, oppresses, etc.; to release; to disengage; to clear; -- followed by from, and sometimes by off; as, to free a captive or a slave; to be freed of these inconveniences.",
	"FEDERAL":    "Pertaining to a league or treaty; derived from an agreement or covenant between parties, especially between nations; constituted by a compact between parties, usually governments or their representatives.",
	"REAL":       "Pertaining to things fixed, permanent, or immovable, as to lands and tenements; as, real property, in distinction from personal or movable property.",
	"VARIOUS":    "Different; diverse; several; manifold; as, men of various names; various occupations; various colors.",
	"HARD":       "Abrupt or explosive in utterance; not aspirated, sibilated, or pronounced with a gradual change of the organs from one position to another; -- said of certain consonants, as c in came, and g in go, as distinguished from the same letters in center, general, etc.",
	"RED":        "Of the color of blood, or of a tint resembling that color; of the hue of that part of the rainbow, or of the solar spectrum, which is furthest from the violet part.",
	"NATURAL":    "Fixed or determined by nature; pertaining to the constitution of a thing; belonging to native character; according to nature; essential; characteristic; not artifical, foreign, assumed, put on, or acquired; as, the natural growth of animals or plants; the natural motion of a gravitating body; natural strength or disposition; the natural heat of the body; natural color.",
	"HOT":        "Having much sensible heat; exciting the feeling of warmth in a great degree; very warm; -- opposed to cold, and exceeding warm in degree; as, a hot stove; hot water or air.",
	"HAPPY":      "Experiencing the effect of favorable fortune; having the feeling arising from the consciousness of well-being or of enjoyment; enjoying good of any kind, as peace, tranquillity, comfort; contented; joyous; as, happy hours, happy thoughts.",
	"READY":      "Prepared for what one is about to do or experience; equipped or supplied with what is needed for some act or event; prepared for immediate movement or action; as, the troops are ready to march; ready for the journey.",
}

func main() {
	if len(os.Args) != 2 {
		log.Fatalf("invalid number of arguments: expect 1, got %d\n", len(os.Args)-1)
	}

	word := strings.ToUpper(os.Args[1])
	meaning, ok := wordToMeaning[word]
	if !ok {
		log.Fatalf("looking up %s: no meaning found", word)
	}

	fmt.Println(meaning)
}
